//
// InterestAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class InterestAPI {

    /**
     Get interest by ID
     
     - parameter interestId: (path) Required. The ID of the interest to retrieve. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ImdbapiInterest
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func iMDbAPIServiceGetInterest(interestId: String,
                                              apiConfiguration: OpenAPIClientAPIConfiguration? = nil) async throws(ErrorResponse) -> ImdbapiInterest {
        let config = apiConfiguration ?? OpenAPIClientAPIConfiguration.shared
        return try await iMDbAPIServiceGetInterestWithRequestBuilder(interestId: interestId, apiConfiguration: config).execute().body
    }

    /**
     Get interest by ID
     - GET /interests/{interestId}
     - Retrieve details of a specific interest using its ID.
     - parameter interestId: (path) Required. The ID of the interest to retrieve. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImdbapiInterest> 
     */
    open class func iMDbAPIServiceGetInterestWithRequestBuilder(interestId: String,
                                                                apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ImdbapiInterest> {
        var localVariablePath = "/interests/{interestId}"
        let interestIdPreEscape = "\(APIHelper.mapValueToPathItem(interestId))"
        let interestIdPostEscape = interestIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{interestId}", with: interestIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImdbapiInterest>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET",
                                                URLString: (localVariableUrlComponents?.string ?? localVariableURLString),
                                                parameters: localVariableParameters,
                                                headers: localVariableHeaderParameters,
                                                requiresAuthentication: false,
                                                apiConfiguration: apiConfiguration)
    }

    /**
     List interest categories
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ImdbapiListListInterestCategoriesResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func iMDbAPIServiceListInterestCategories(apiConfiguration: OpenAPIClientAPIConfiguration? = nil) async throws(ErrorResponse) -> ImdbapiListListInterestCategoriesResponse {
        let config = apiConfiguration ?? OpenAPIClientAPIConfiguration.shared
        return try await iMDbAPIServiceListInterestCategoriesWithRequestBuilder(apiConfiguration: config).execute().body
    }

    /**
     List interest categories
     - GET /interests
     - Retrieve all interest categories available in the IMDb API.
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImdbapiListListInterestCategoriesResponse> 
     */
    open class func iMDbAPIServiceListInterestCategoriesWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration? = nil) -> RequestBuilder<ImdbapiListListInterestCategoriesResponse> {
        let config = apiConfiguration ?? OpenAPIClientAPIConfiguration.shared
        let localVariablePath = "/interests"
        let localVariableURLString = config.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImdbapiListListInterestCategoriesResponse>.Type = config.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET",
                                                URLString: (localVariableUrlComponents?.string ?? localVariableURLString),
                                                parameters: localVariableParameters,
                                                headers: localVariableHeaderParameters,
                                                requiresAuthentication: false,
                                                apiConfiguration: config)
    }
}

