//
// ImdbapiNameMeterRanking.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The NameMeterRanking message represents the IMDb popularity meter ranking for a person, including their current rank, change direction, and difference from the previous measurement.
 This ranking is used to indicate the popularity of the person over time. */
public struct ImdbapiNameMeterRanking: Sendable, Codable, ParameterConvertible, Hashable {

    /** The current rank of the person in the IMDb popularity meter. */
    public var currentRank: Int?
    /** The direction of the change in rank, which can be \"UP\", \"DOWN\", or \"none\". */
    public var changeDirection: String?
    /** The difference in rank compared to the previous measurement. Positive for an increase, negative for a decrease, and zero for no change. */
    public var difference: Int?

    public init(currentRank: Int? = nil, changeDirection: String? = nil, difference: Int? = nil) {
        self.currentRank = currentRank
        self.changeDirection = changeDirection
        self.difference = difference
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentRank
        case changeDirection
        case difference
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currentRank, forKey: .currentRank)
        try container.encodeIfPresent(changeDirection, forKey: .changeDirection)
        try container.encodeIfPresent(difference, forKey: .difference)
    }
}

