//
// ImdbapiBatchGetNamesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for batch getting names by their IDs. */
public struct ImdbapiBatchGetNamesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of names retrieved by their IMDb IDs. */
    public var names: [ImdbapiName]?

    public init(names: [ImdbapiName]? = nil) {
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case names
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(names, forKey: .names)
    }
}

