//
// ImdbapiCompanyCredit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiCompanyCredit: Sendable, Codable, ParameterConvertible, Hashable {

    public var company: ImdbapiCompany?
    /** Category of the company credit, such as production, sales, distribution, etc. */
    public var category: String?
    /** Countries where the company is based or operates. */
    public var countries: [ImdbapiCountry]?
    public var yearsInvolved: ImdbapiYearsInvolved?
    public var attributes: [String]?

    public init(company: ImdbapiCompany? = nil, category: String? = nil, countries: [ImdbapiCountry]? = nil, yearsInvolved: ImdbapiYearsInvolved? = nil, attributes: [String]? = nil) {
        self.company = company
        self.category = category
        self.countries = countries
        self.yearsInvolved = yearsInvolved
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case company
        case category
        case countries
        case yearsInvolved
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(company, forKey: .company)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(countries, forKey: .countries)
        try container.encodeIfPresent(yearsInvolved, forKey: .yearsInvolved)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

