//
// ImdbapiPrecisionDate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The PrecisionDate message represents a specific date, typically used for birth dates, death dates, or release dates. */
public struct ImdbapiPrecisionDate: Sendable, Codable, ParameterConvertible, Hashable {

    /** The year of the date, represented as an integer. */
    public var year: Int?
    /** The month of the date, represented as an integer. */
    public var month: Int?
    /** The day of the date, represented as an integer. */
    public var day: Int?

    public init(year: Int? = nil, month: Int? = nil, day: Int? = nil) {
        self.year = year
        self.month = month
        self.day = day
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case year
        case month
        case day
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(month, forKey: .month)
        try container.encodeIfPresent(day, forKey: .day)
    }
}

