//
// ImdbapiImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The Image message represents an image associated with a person or title in the IMDb database. */
public struct ImdbapiImage: Sendable, Codable, ParameterConvertible, Hashable {

    /** The URL of the image, which can be used to access the image file. */
    public var url: String?
    /** The width of the image in pixels. */
    public var width: Int?
    /** The height of the image in pixels. */
    public var height: Int?
    /** The type of the image, such as \"poster\", \"still_frame\", \"event\", etc. */
    public var type: String?

    public init(url: String? = nil, width: Int? = nil, height: Int? = nil, type: String? = nil) {
        self.url = url
        self.width = width
        self.height = height
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case width
        case height
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

