//
// ImdbapiAKA.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The AKA (Also Known As) message represents alternative titles for a movie or TV show in different languages and countries. */
public struct ImdbapiAKA: Sendable, Codable, ParameterConvertible, Hashable {

    /** The display text of the title in the specified language and country. */
    public var text: String?
    public var country: ImdbapiCountry?
    public var language: ImdbapiLanguage?
    /** Additional attributes related to the title, such as \"original title\", \"working title\", or \"alternative title\". */
    public var attributes: [String]?

    public init(text: String? = nil, country: ImdbapiCountry? = nil, language: ImdbapiLanguage? = nil, attributes: [String]? = nil) {
        self.text = text
        self.country = country
        self.language = language
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case country
        case language
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

