//
// ImdbapiSearchTitlesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for searching titles. */
public struct ImdbapiSearchTitlesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of titles matching the search query. */
    public var titles: [ImdbapiTitle]?

    public init(titles: [ImdbapiTitle]? = nil) {
        self.titles = titles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case titles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(titles, forKey: .titles)
    }
}

