//
// ImdbapiParentsGuide.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiParentsGuide: Sendable, Codable, ParameterConvertible, Hashable {

    public var category: ImdbapiParentsGuideCategory?
    public var severityBreakdowns: [ImdbapiParentsGuideSeverity]?
    public var reviews: [ImdbapiParentsGuideReview]?

    public init(category: ImdbapiParentsGuideCategory? = nil, severityBreakdowns: [ImdbapiParentsGuideSeverity]? = nil, reviews: [ImdbapiParentsGuideReview]? = nil) {
        self.category = category
        self.severityBreakdowns = severityBreakdowns
        self.reviews = reviews
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case severityBreakdowns
        case reviews
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(severityBreakdowns, forKey: .severityBreakdowns)
        try container.encodeIfPresent(reviews, forKey: .reviews)
    }
}

