//
// ImdbapiListTitleImagesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiListTitleImagesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of images associated with the title. */
    public var images: [ImdbapiImage]?
    /** Total count of images associated with the title. */
    public var totalCount: Int?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(images: [ImdbapiImage]? = nil, totalCount: Int? = nil, nextPageToken: String? = nil) {
        self.images = images
        self.totalCount = totalCount
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case images
        case totalCount
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(images, forKey: .images)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

