//
// ImdbapiListListInterestCategoriesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing interest categories. */
public struct ImdbapiListListInterestCategoriesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of available interest categories. */
    public var categories: [ImdbapiInterestCategory]?

    public init(categories: [ImdbapiInterestCategory]? = nil) {
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categories, forKey: .categories)
    }
}

