//
// ImdbapiParentsGuideSeverity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiParentsGuideSeverity: Sendable, Codable, ParameterConvertible, Hashable {

    public var severityLevel: String?
    public var voteCount: Int?

    public init(severityLevel: String? = nil, voteCount: Int? = nil) {
        self.severityLevel = severityLevel
        self.voteCount = voteCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case severityLevel
        case voteCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(severityLevel, forKey: .severityLevel)
        try container.encodeIfPresent(voteCount, forKey: .voteCount)
    }
}

