//
// ImdbapiMoney.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiMoney: Sendable, Codable, ParameterConvertible, Hashable {

    /** The amount of money in the box office. */
    public var amount: String?
    /** The currency of the money. */
    public var currency: String?

    public init(amount: String? = nil, currency: String? = nil) {
        self.amount = amount
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(currency, forKey: .currency)
    }
}

