//
// ImdbapiListTitleAwardNominationsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing award nominations associated with a title. */
public struct ImdbapiListTitleAwardNominationsResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var stats: ImdbapiAwardNominationStats?
    /** List of award nominations associated with the title. */
    public var awardNominations: [ImdbapiAwardNomination]?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(stats: ImdbapiAwardNominationStats? = nil, awardNominations: [ImdbapiAwardNomination]? = nil, nextPageToken: String? = nil) {
        self.stats = stats
        self.awardNominations = awardNominations
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stats
        case awardNominations
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(stats, forKey: .stats)
        try container.encodeIfPresent(awardNominations, forKey: .awardNominations)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

