//
// ImdbapiListTitlesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing titles. */
public struct ImdbapiListTitlesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of titles matching the request criteria. */
    public var titles: [ImdbapiTitle]?
    /** Total number of titles matching the request criteria. */
    public var totalCount: Int?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(titles: [ImdbapiTitle]? = nil, totalCount: Int? = nil, nextPageToken: String? = nil) {
        self.titles = titles
        self.totalCount = totalCount
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case titles
        case totalCount
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(titles, forKey: .titles)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

