//
// ImdbapiNameRelationship.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The NameRelationship message represents a relationship between two names in the IMDb database, such as family members, spouses, parents, children, etc.
 Each relationship includes the related name, the type of relationship, and any additional attributes associated with the relationship. */
public struct ImdbapiNameRelationship: Sendable, Codable, ParameterConvertible, Hashable {

    public var name: ImdbapiName?
    /** The type of relationship, such as \"spouse\", \"parent\", \"child\", etc. */
    public var relationType: String?
    /** Additional attributes associated with the relationship. */
    public var attributes: [String]?

    public init(name: ImdbapiName? = nil, relationType: String? = nil, attributes: [String]? = nil) {
        self.name = name
        self.relationType = relationType
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case relationType
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(relationType, forKey: .relationType)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

