//
// ImdbapiListTitleCreditsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing credits associated with a title. */
public struct ImdbapiListTitleCreditsResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of credits associated with the title. */
    public var credits: [ImdbapiCredit]?
    /** Total count of credits associated with the title. */
    public var totalCount: Int?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(credits: [ImdbapiCredit]? = nil, totalCount: Int? = nil, nextPageToken: String? = nil) {
        self.credits = credits
        self.totalCount = totalCount
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credits
        case totalCount
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(credits, forKey: .credits)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

