//
// ImdbapiInterestCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** InterestCategory represents a category of interests in the IMDB API. */
public struct ImdbapiInterestCategory: Sendable, Codable, ParameterConvertible, Hashable {

    /** Unique identifier for the interest category. */
    public var category: String?
    /** A list of interests that belong to this category. */
    public var interests: [ImdbapiInterest]?

    public init(category: String? = nil, interests: [ImdbapiInterest]? = nil) {
        self.category = category
        self.interests = interests
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case interests
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(interests, forKey: .interests)
    }
}

