//
// ImdbapiCertificate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The Certificate message represents a content rating certificate for a title. */
public struct ImdbapiCertificate: Sendable, Codable, ParameterConvertible, Hashable {

    /** The rating of the certificate, such as \"PG-13\", \"R\", etc. */
    public var rating: String?
    public var country: ImdbapiCountry?
    public var attributes: [String]?

    public init(rating: String? = nil, country: ImdbapiCountry? = nil, attributes: [String]? = nil) {
        self.rating = rating
        self.country = country
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rating
        case country
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

