//
// ImdbapiNameTrivia.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** NameTrivia represents a trivia fact about a person (name). */
public struct ImdbapiNameTrivia: Sendable, Codable, ParameterConvertible, Hashable {

    /** The unique identifier for the trivia. */
    public var id: String?
    /** The trivia body text. */
    public var text: String?
    /** The number of users who have expressed interest in this trivia. */
    public var interestCount: Int?
    /** The number of votes this trivia has received. */
    public var voteCount: Int?

    public init(id: String? = nil, text: String? = nil, interestCount: Int? = nil, voteCount: Int? = nil) {
        self.id = id
        self.text = text
        self.interestCount = interestCount
        self.voteCount = voteCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case text
        case interestCount
        case voteCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(interestCount, forKey: .interestCount)
        try container.encodeIfPresent(voteCount, forKey: .voteCount)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ImdbapiNameTrivia: Identifiable {}
