//
// ImdbapiLanguage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The AKA (Also Known As) message represents alternative titles for a movie or TV show in different languages and countries. */
public struct ImdbapiLanguage: Sendable, Codable, ParameterConvertible, Hashable {

    public var code: String?
    /** The name of the language in English. */
    public var name: String?

    public init(code: String? = nil, name: String? = nil) {
        self.code = code
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

