//
// ImdbapiListNameRelationshipsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing relationships associated with a name. */
public struct ImdbapiListNameRelationshipsResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of relationships associated with the name. */
    public var relationships: [ImdbapiNameRelationship]?

    public init(relationships: [ImdbapiNameRelationship]? = nil) {
        self.relationships = relationships
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relationships
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(relationships, forKey: .relationships)
    }
}

