//
// ImdbapiReleaseDate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The ReleaseDate message represents the release date of a title in a specific country. */
public struct ImdbapiReleaseDate: Sendable, Codable, ParameterConvertible, Hashable {

    public var country: ImdbapiCountry?
    public var releaseDate: ImdbapiPrecisionDate?
    /** The attributes field contains additional attributes related to the release date.
     These attributes can include information such as the format of the release (e.g., \"Theatrical\", \"DVD\", \"Blu-ray\"). */
    public var attributes: [String]?

    public init(country: ImdbapiCountry? = nil, releaseDate: ImdbapiPrecisionDate? = nil, attributes: [String]? = nil) {
        self.country = country
        self.releaseDate = releaseDate
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case country
        case releaseDate
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(releaseDate, forKey: .releaseDate)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

