//
// ImdbapiListTitleReleaseDatesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing release dates associated with a title. */
public struct ImdbapiListTitleReleaseDatesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of release dates associated with the title. */
    public var releaseDates: [ImdbapiReleaseDate]?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(releaseDates: [ImdbapiReleaseDate]? = nil, nextPageToken: String? = nil) {
        self.releaseDates = releaseDates
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case releaseDates
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(releaseDates, forKey: .releaseDates)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

