//
// ImdbapiListStarMetersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing star meter rankings. */
public struct ImdbapiListStarMetersResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of names with their star meter rankings. */
    public var names: [ImdbapiName]?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(names: [ImdbapiName]? = nil, nextPageToken: String? = nil) {
        self.names = names
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case names
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(names, forKey: .names)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

