//
// ImdbapiParentsGuideReview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiParentsGuideReview: Sendable, Codable, ParameterConvertible, Hashable {

    public var text: String?
    public var isSpoiler: Bool?

    public init(text: String? = nil, isSpoiler: Bool? = nil) {
        self.text = text
        self.isSpoiler = isSpoiler
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case isSpoiler
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(isSpoiler, forKey: .isSpoiler)
    }
}

