//
// ImdbapiCredit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The Credit message represents a credit for a person in a title. */
public struct ImdbapiCredit: Sendable, Codable, ParameterConvertible, Hashable {

    public var title: ImdbapiTitle?
    public var name: ImdbapiName?
    /** The category of the credit. */
    public var category: String?
    /** The characters played by the actor/actress in the title. */
    public var characters: [String]?
    /** The number of episodes in which the person has appeared. */
    public var episodeCount: Int?

    public init(title: ImdbapiTitle? = nil, name: ImdbapiName? = nil, category: String? = nil, characters: [String]? = nil, episodeCount: Int? = nil) {
        self.title = title
        self.name = name
        self.category = category
        self.characters = characters
        self.episodeCount = episodeCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case name
        case category
        case characters
        case episodeCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(characters, forKey: .characters)
        try container.encodeIfPresent(episodeCount, forKey: .episodeCount)
    }
}

