//
// ImdbapiListTitleAKAsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing AKAs (Also Known As) associated with a title. */
public struct ImdbapiListTitleAKAsResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of AKAs associated with the title. */
    public var akas: [ImdbapiAKA]?

    public init(akas: [ImdbapiAKA]? = nil) {
        self.akas = akas
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case akas
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(akas, forKey: .akas)
    }
}

