//
// ImdbapiMetacritic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Metacritic information for a movie or TV show. */
public struct ImdbapiMetacritic: Sendable, Codable, ParameterConvertible, Hashable {

    /** Metacritic URL. */
    public var url: String?
    /** Metacritic score. */
    public var score: Int?
    /** Number of reviews. */
    public var reviewCount: Int?

    public init(url: String? = nil, score: Int? = nil, reviewCount: Int? = nil) {
        self.url = url
        self.score = score
        self.reviewCount = reviewCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case score
        case reviewCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(score, forKey: .score)
        try container.encodeIfPresent(reviewCount, forKey: .reviewCount)
    }
}

