//
// ImdbapiSeason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiSeason: Sendable, Codable, ParameterConvertible, Hashable {

    public var season: String?
    public var episodeCount: Int?

    public init(season: String? = nil, episodeCount: Int? = nil) {
        self.season = season
        self.episodeCount = episodeCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case season
        case episodeCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(season, forKey: .season)
        try container.encodeIfPresent(episodeCount, forKey: .episodeCount)
    }
}

