//
// ImdbapiParentsGuideCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** ParentsGuideCategory defines the categories for the Parents Guide.   - SEXUAL_CONTENT: Sex &amp; Nudity  - VIOLENCE: Violence &amp; Gore  - PROFANITY: Profanity  - ALCOHOL_DRUGS: Alcohol, Drugs &amp; Smoking  - FRIGHTENING_INTENSE_SCENES: Frightening &amp; Intense Scenes */
public enum ImdbapiParentsGuideCategory: String, Sendable, Codable, CaseIterable {
    case sexualContent = "SEXUAL_CONTENT"
    case violence = "VIOLENCE"
    case profanity = "PROFANITY"
    case alcoholDrugs = "ALCOHOL_DRUGS"
    case frighteningIntenseScenes = "FRIGHTENING_INTENSE_SCENES"
}
