//
// ImdbapiSortOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  - ASC: Sort in ascending order.  - DESC: Sort in descending order. */
public enum ImdbapiSortOrder: String, Sendable, Codable, CaseIterable {
    case asc = "ASC"
    case desc = "DESC"
}
