//
// ImdbapiListTitleParentsGuideResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing parents guide associated with a title. */
public struct ImdbapiListTitleParentsGuideResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of parents guide entries associated with the title. */
    public var parentsGuide: [ImdbapiParentsGuide]?

    public init(parentsGuide: [ImdbapiParentsGuide]? = nil) {
        self.parentsGuide = parentsGuide
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parentsGuide
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(parentsGuide, forKey: .parentsGuide)
    }
}

