//
// ImdbapiListTitleVideosResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiListTitleVideosResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of videos associated with the title. */
    public var videos: [ImdbapiVideo]?
    /** Total count of videos associated with the title. */
    public var totalCount: Int?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(videos: [ImdbapiVideo]? = nil, totalCount: Int? = nil, nextPageToken: String? = nil) {
        self.videos = videos
        self.totalCount = totalCount
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videos
        case totalCount
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(videos, forKey: .videos)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

