//
// ImdbapiBoxOffice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiBoxOffice: Sendable, Codable, ParameterConvertible, Hashable {

    public var domesticGross: ImdbapiMoney?
    public var worldwideGross: ImdbapiMoney?
    public var openingWeekendGross: ImdbapiOpeningWeekendGross?
    public var productionBudget: ImdbapiMoney?

    public init(domesticGross: ImdbapiMoney? = nil, worldwideGross: ImdbapiMoney? = nil, openingWeekendGross: ImdbapiOpeningWeekendGross? = nil, productionBudget: ImdbapiMoney? = nil) {
        self.domesticGross = domesticGross
        self.worldwideGross = worldwideGross
        self.openingWeekendGross = openingWeekendGross
        self.productionBudget = productionBudget
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domesticGross
        case worldwideGross
        case openingWeekendGross
        case productionBudget
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(domesticGross, forKey: .domesticGross)
        try container.encodeIfPresent(worldwideGross, forKey: .worldwideGross)
        try container.encodeIfPresent(openingWeekendGross, forKey: .openingWeekendGross)
        try container.encodeIfPresent(productionBudget, forKey: .productionBudget)
    }
}

