//
// ImdbapiRating.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The Rating message represents the aggregate rating and votes count for a title. */
public struct ImdbapiRating: Sendable, Codable, ParameterConvertible, Hashable {

    /** The aggregate_rating field contains the average rating of the title, typically on a scale from 1 to 10. */
    public var aggregateRating: Float?
    /** The votes_count field contains the total number of votes cast for the title. */
    public var voteCount: Int?

    public init(aggregateRating: Float? = nil, voteCount: Int? = nil) {
        self.aggregateRating = aggregateRating
        self.voteCount = voteCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aggregateRating
        case voteCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(aggregateRating, forKey: .aggregateRating)
        try container.encodeIfPresent(voteCount, forKey: .voteCount)
    }
}

