//
// ImdbapiYearsInvolved.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiYearsInvolved: Sendable, Codable, ParameterConvertible, Hashable {

    public var startYear: Int?
    public var endYear: Int?

    public init(startYear: Int? = nil, endYear: Int? = nil) {
        self.startYear = startYear
        self.endYear = endYear
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startYear
        case endYear
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startYear, forKey: .startYear)
        try container.encodeIfPresent(endYear, forKey: .endYear)
    }
}

