//
// ImdbapiAwardNominationStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiAwardNominationStats: Sendable, Codable, ParameterConvertible, Hashable {

    public var nominationCount: Int?
    public var winCount: Int?

    public init(nominationCount: Int? = nil, winCount: Int? = nil) {
        self.nominationCount = nominationCount
        self.winCount = winCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nominationCount
        case winCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nominationCount, forKey: .nominationCount)
        try container.encodeIfPresent(winCount, forKey: .winCount)
    }
}

