//
// ImdbapiInterest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Interest represents a specific interest in the IMDB API. */
public struct ImdbapiInterest: Sendable, Codable, ParameterConvertible, Hashable {

    /** Unique identifier for the interest. */
    public var id: String?
    /** The name of the interest, e.g., \"Action\", \"Action Epic\", \"Adult Animation\", etc. */
    public var name: String?
    public var primaryImage: ImdbapiImage?
    /** A brief description of the interest, which can include details about the genre or type. */
    public var description: String?
    /** Indicates whether the interest is a subgenre of another genre. */
    public var isSubgenre: Bool?
    /** A list of similar interests that are related to this interest. */
    public var similarInterests: [ImdbapiInterest]?

    public init(id: String? = nil, name: String? = nil, primaryImage: ImdbapiImage? = nil, description: String? = nil, isSubgenre: Bool? = nil, similarInterests: [ImdbapiInterest]? = nil) {
        self.id = id
        self.name = name
        self.primaryImage = primaryImage
        self.description = description
        self.isSubgenre = isSubgenre
        self.similarInterests = similarInterests
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case primaryImage
        case description
        case isSubgenre
        case similarInterests
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(primaryImage, forKey: .primaryImage)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isSubgenre, forKey: .isSubgenre)
        try container.encodeIfPresent(similarInterests, forKey: .similarInterests)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ImdbapiInterest: Identifiable {}
