//
// ImdbapiOpeningWeekendGross.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiOpeningWeekendGross: Sendable, Codable, ParameterConvertible, Hashable {

    public var gross: ImdbapiMoney?
    public var weekendEndDate: ImdbapiPrecisionDate?

    public init(gross: ImdbapiMoney? = nil, weekendEndDate: ImdbapiPrecisionDate? = nil) {
        self.gross = gross
        self.weekendEndDate = weekendEndDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gross
        case weekendEndDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gross, forKey: .gross)
        try container.encodeIfPresent(weekendEndDate, forKey: .weekendEndDate)
    }
}

