//
// ImdbapiListTitleEpisodesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiListTitleEpisodesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of episodes associated with the title. */
    public var episodes: [ImdbapiEpisode]?
    /** The total number of episodes that have aired for this title. */
    public var totalCount: Int?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(episodes: [ImdbapiEpisode]? = nil, totalCount: Int? = nil, nextPageToken: String? = nil) {
        self.episodes = episodes
        self.totalCount = totalCount
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case episodes
        case totalCount
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(episodes, forKey: .episodes)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

