//
// ImdbapiTitleSortBy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**
 - SORT_BY_POPULARITY: Sort by popularity. This is used to rank titles based on their popularity,
 which can be influenced by various factors such as viewership, ratings, and cultural impact.
 - SORT_BY_RELEASE_DATE: Sort by release date. This is used to rank titles based on their release dates,
 with newer titles typically appearing before older ones.
 - SORT_BY_USER_RATING: Sort by user rating. This is used to rank titles based on the average user rating,
 which reflects the overall audience reception.
 - SORT_BY_USER_RATING_COUNT: Sort by user rating count. This is used to rank titles based on
 the number of user ratings they have received, which can indicate the level of engagement or popularity among viewers.
 - SORT_BY_YEAR: Sort by year. This is used to rank titles based on their release year, with newer titles typically appearing before older ones. */
public enum ImdbapiTitleSortBy: String, Sendable, Codable, CaseIterable {
    case sortByPopularity = "SORT_BY_POPULARITY"
    case sortByReleaseDate = "SORT_BY_RELEASE_DATE"
    case sortByUserRating = "SORT_BY_USER_RATING"
    case sortByUserRatingCount = "SORT_BY_USER_RATING_COUNT"
    case sortByYear = "SORT_BY_YEAR"
}
