//
// ImdbapiListTitleCompanyCreditsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing company credits associated with a title. */
public struct ImdbapiListTitleCompanyCreditsResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of company credits associated with the title. */
    public var companyCredits: [ImdbapiCompanyCredit]?
    /** Total count of company credits matched for listing. */
    public var totalCount: Int?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(companyCredits: [ImdbapiCompanyCredit]? = nil, totalCount: Int? = nil, nextPageToken: String? = nil) {
        self.companyCredits = companyCredits
        self.totalCount = totalCount
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case companyCredits
        case totalCount
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(companyCredits, forKey: .companyCredits)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

