//
// ImdbapiListTitleCertificatesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing certificates associated with a title. */
public struct ImdbapiListTitleCertificatesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of certificates associated with the title. */
    public var certificates: [ImdbapiCertificate]?
    /** Total count of certificates associated with the title. */
    public var totalCount: Int?

    public init(certificates: [ImdbapiCertificate]? = nil, totalCount: Int? = nil) {
        self.certificates = certificates
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case certificates
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(certificates, forKey: .certificates)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
    }
}

