//
// ImdbapiListNameTriviaResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response message for listing trivia associated with a name. */
public struct ImdbapiListNameTriviaResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of trivia entries associated with the name. */
    public var triviaEntries: [ImdbapiNameTrivia]?
    /** Total count of trivia entries associated with the name. */
    public var totalCount: Int?
    /** Token for the next page of results, if applicable. */
    public var nextPageToken: String?

    public init(triviaEntries: [ImdbapiNameTrivia]? = nil, totalCount: Int? = nil, nextPageToken: String? = nil) {
        self.triviaEntries = triviaEntries
        self.totalCount = totalCount
        self.nextPageToken = nextPageToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case triviaEntries
        case totalCount
        case nextPageToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(triviaEntries, forKey: .triviaEntries)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
    }
}

