//
// ImdbapiListTitleSeasonsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImdbapiListTitleSeasonsResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** List of seasons associated with the title. */
    public var seasons: [ImdbapiSeason]?

    public init(seasons: [ImdbapiSeason]? = nil) {
        self.seasons = seasons
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seasons
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(seasons, forKey: .seasons)
    }
}

