//
// RpcStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RpcStatus: Sendable, Codable, ParameterConvertible, Hashable {

    public var code: Int?
    public var message: String?
    public var details: [ProtobufAny]?

    public init(code: Int? = nil, message: String? = nil, details: [ProtobufAny]? = nil) {
        self.code = code
        self.message = message
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(details, forKey: .details)
    }
}

